### ISSUE TITLE
Bring in npm publication repo to clog org

### ISSUE THREAD

**Issue by kentcdodds** [clog-tool/clog-cli#73]
I don't mind maintaining [the repo I'm using](https://github.com/kentcdodds/clog-cli) to distribute clog via `npm`, but do you think it would make more sense as part of the `clog-tool` org? I'd happily transfer it to this org and change it's name to `npm-distribution` or something (so it doesn't conflict with what's being discussed in #70).

**Comment by kbknapp** [comment]
Thinking out loud here; would it be a good idea to do each of the package repos this way? It'd make it a little easier to track changes for things like Homebrew, AUR, npm, etc.

**Comment by kentcdodds** [comment]
+1 for that. Though based on [this comment](https://github.com/kentcdodds/clog-cli/issues/2#issuecomment-128745378) I'm thinking that the npm version will actually just download the latest version of `clog` for the platform. Meaning that it should never have to be updated. It'll always just get the latest version and if someone wants an older version they can install it manually... That's what I'm thinking right now anyway...

**Comment by vyp** [comment]
May be a bit off topic, but now that cargo has `cargo install` (https://github.com/rust-lang/rfcs/pull/1200#issuecomment-131227462), do you guys think we don't need the AUR packages at least? (not sure about npm/homebrew)

**Comment by vyp** [comment]
After clog targets the next release of rust/cargo that is.

**Comment by kbknapp** [comment]
I would still vote yes on the AUR and other repos. Because I can't speak for others, but I'm always way more comfortable with my system package manager, instead of things like `npm`, `cargo`, `pip`, etc. Plus it allows users who don't have `cargo` or even use Rust.

**Comment by cburgdorf** [comment]
> Plus it allows users who don't have cargo or even use Rust.

I share @kbknapp 's opinion
