### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Ryman** [clog-tool/clog-cli#76]
The [conventional changelog](https://github.com/ajoslin/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md) description lists:
> Breaking Changes are detected as such if the footer contains a line starting with BREAKING CHANGE: (with optional newlines) The rest of the commit message is then used for this.

I couldn't find anything in the repo referencing 'breaking', and the tool hasn't been picking them up, so I'm assuming this is unimplemented. Is this a missing feature, or have I overlooked something?

**Comment by cburgdorf** [comment]
Note that this is the repository for the CLI. Clog is split into library and CLI. This feature should actually be implemented. https://github.com/clog-tool/clog-lib/blob/ce5df5d02ce01914d3cf97d8502b9312bf64aa26/src/clog.rs#L130

**Comment by Ryman** [comment]
Ah, okay, but it looks like it's only used to find commits and there's no section in the outputted changelog though?

**Comment by kbknapp** [comment]
@Ryan correct. It would be a simple addition to actually output them in the changelog. I think the current implementation was a placeholder and just hasn't been changed to actually list them.

**Comment by kbknapp** [comment]
Leaving this open for tracking, but it's actually https://github.com/clog-tool/clog-lib/issues/5

**Comment by kbknapp** [comment]
Closed with https://github.com/clog-tool/clog-lib/issues/5
