### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by elranu** [clog-tool/clog-cli#89]
Hi, 
I just downloaded clog-v0.7.0_windows-x64.zip binary and when I executed I get the following error:

`
clog
thread '<main>' panicked at 'index 0 and/or 8 in``do not lie on character boundary', C:/bot/slave/stable-dist-rustc-win-64/build/src/libcore\str/mod.rs:1
` 

Do you know how to solve it? I have Win 10 and I don't have installed Rust.

Thanks

**Comment by cburgdorf** [comment]
Hey @elranu 

How did you run it? From the command line I guess? Can you run `clog --help` and see if that gives you any output?

**Comment by elranu** [comment]
hehehe clog --help works. Sorry for that. I have thought that if I run clog without arguments should give me some info... like clog --help... thanks.

Sorry  again

**Comment by cburgdorf** [comment]
Well just running `clog` without any arguments shouldn't produce such error actually. Did you invoke it from the command line to get this error?

**Comment by elranu** [comment]
yes from the CMD

Thanks

**Comment by kbknapp** [comment]
I need to re-build for windows, 0.7 is old and it's entirely possible that's the reason. I don't have my windows machine handy at the moment. @elranu can you compile from the master branch of this repo?
