### ISSUE TITLE
`--setversion` flag not working for ubuntu.

### ISSUE THREAD

**Issue by jtk54** [clog-tool/clog-cli#98]
Running `clog` on Ubuntu (3.13.0-105-generic #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux) with `--setversion` doesn't set the version in the changelog.

Sample command: `clog -r <REPO> --from <HASH> --setversion 1.7.0 | less`

Expected: 

```markdown
<a name="1.7.0"></a>
##  (2017-01-03)


#### Features

* **package.json:**  new minimal package.json. ([a4715fee](https://github.com/jtk54/changelog-test/commit/a4715feee1281f593b7c17e2e10d9309869c79be))

#### Bug Fixes

* **BULLETS:**
  *  Differentiated bullets. ([dd8e477a](https://github.com/jtk54/changelog-test/commit/dd8e477a31235f141132f81f34cd039f1a8d08b9))
  *  Too many bullets. ([df0446e9](https://github.com/jtk54/changelog-test/commit/df0446e9effef13fabe1f56fbf44b1275b0e8b4d))
* **HEADING:**  Heading 2 fix. ([e01cb7a8](https://github.com/jtk54/changelog-test/commit/e01cb7a824e20debbd098b14f4510e6ba7635b03))
* **README:**  Added things. (#1) ([e5773e64](https://github.com/jtk54/changelog-test/commit/e5773e6489902799e9760df5c69d29e0f7e3894e))
```

Actual:

```markdown
<a name=""></a>
##  (2017-01-03)


#### Features

* **package.json:**  new minimal package.json. ([a4715fee](https://github.com/jtk54/changelog-test/commit/a4715feee1281f593b7c17e2e10d9309869c79be))

#### Bug Fixes

* **BULLETS:**
  *  Differentiated bullets. ([dd8e477a](https://github.com/jtk54/changelog-test/commit/dd8e477a31235f141132f81f34cd039f1a8d08b9))
  *  Too many bullets. ([df0446e9](https://github.com/jtk54/changelog-test/commit/df0446e9effef13fabe1f56fbf44b1275b0e8b4d))
* **HEADING:**  Heading 2 fix. ([e01cb7a8](https://github.com/jtk54/changelog-test/commit/e01cb7a824e20debbd098b14f4510e6ba7635b03))
* **README:**  Added things. (#1) ([e5773e64](https://github.com/jtk54/changelog-test/commit/e5773e6489902799e9760df5c69d29e0f7e3894e))
```

Using the minor version flag `-m` worked fine, but I want to use a different version format in the changelog output than what the git tags look like. I can always manually add the version in, but it would be nice to automate this.

**Comment by kbknapp** [comment]
@jtk54 which version of `clog` are you using?

**Comment by jtk54** [comment]
clog 0.9.2, I just did a fresh install of rust and cargo, and used `cargo install clog-cli`.

**Comment by jtk54** [comment]
If it helps, `rustc` is at 1.14.0 (e8a012324 2016-12-16) and `cargo` is at 0.15.0-nightly (298a012 2016-12-20).

**Comment by jtk54** [comment]
Still seeing this issue, do you need more information to debug? Are you able to reproduce?

**Comment by kbknapp** [comment]
Sorry, I some other issues and work come up! I'll see if I can reproduce it tonight when I get home. Also, do you have any `.clog.toml` in use?

**Comment by jtk54** [comment]
No worries, just checking in. I'm not using a `.clog.toml` to specify output.

**Comment by jtk54** [comment]
Following up on this. I just compiled `clog` locally from source to try and reproduce the issue with `--setversion` I was seeing and everything was working fine.

This makes me think that the `clog` artifact published to the `cargo` registry is out of date. When I installed with

```
cargo install clog-cli
```

the `setversion` issue persists. When I clone the git repo and install from HEAD using

```
cargo install
```

from the root directory, everything works properly. Let me know if you can reproduce this. For now, everything is good on my end -- I'll remember to install from source : D

**Comment by kbknapp** [comment]
I just pushed a new version to crates.io so hopefully that fixes this! Let me know if this issue persists. Sorry for such a long wait!

**Comment by jtk54** [comment]
Bumping up to clog 0.9.3 from crates.io worked for me, thanks for following up : D
