### ISSUE TITLE
No output for basic clog command

### ISSUE THREAD

**Issue by philwinder** [clog-tool/clog-cli#99]
Hi, hopefully a silly one.

This is what I have:
```
$ git log --oneline -3 | cat
529b275 chore(build): push correct latest image
f3e9789 chore(build): add push of latest image to release
8bad680 chore(build): fix circle tag regex and include docker push in release
$ ./clog
<a name=""></a>
##  (2017-01-27)

```
Note how there is no output in the changelog.

I also cloned your repo and that did work. So i suspect that it's an issue with the `chore` word? But that's ok according to: https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md

BTW, I find the fact that there is no standardisation on this a bit worrying.

**Comment by kbknapp** [comment]
The `chore` keyword isn't picked up by default and is meant to be sort of like a comment. If you *want* chore to be picked up, add a `.clog.toml` file with the following tables:

```toml
[sections]
Chores = ["chore"]
```

`Chores` could be anyhting you want the heading to read when `chore` keys are found, multiple words are also OK so long as they're surrounded by quotes:

```toml
[sections]
"My Chores" = ["chore"]
```

**Comment by philwinder** [comment]
Apologies, you are right. Thank you.
